[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/",
    "@solmate/=lib/solmate/src/"
]

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing settings
verbosity = 2
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base_testnet = "${BASE_TESTNET_RPC}"
base = "${BASE_RPC_URL}"

[etherscan]
base_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }

